databases:
  - name: filq-sql
    databaseName: filq_sql
    user: filq_sql_user

services:
  - type: web
    name: filq-be-2
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: filq-sql
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false