source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.6'

gem 'rails', '~> 6.0.6', '>= 6.0.6.1'
gem 'pg'
gem 'puma', '~> 4.1'
gem 'httparty'
gem 'sass-rails', '>= 6'
gem 'doorkeeper', '5.4.0'
gem 'webpacker', '~> 4.0'
gem 'rack-cors'
gem 'turbolinks', '~> 5'
gem 'rubyzip'
gem 'jbuilder', '~> 2.7'
gem 'whenever', require: false
gem 'will_paginate', '~> 3.1.0'
gem 'dotenv-rails'
gem 'bcrypt', '~> 3.1.7'
gem 'bootsnap', '>= 1.4.2', require: false

group :development, :test do
  gem 'apipie-rails'
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'database_cleaner'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'parallel_tests'
  gem 'rubocop-rails', require: false
  gem 'simplecov', require: false
end

group :development do
  gem 'annotate'
  gem 'listen', '~> 3.2'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of web drivers to run system tests with browsers
  gem 'webdrivers'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
